### ISSUE TITLE
Q: verbosity level 4 (debug) does not log POST data message

### ISSUE THREAD

**Issue by ukrit-himakoon** [nicolasff/webdis#116]
Hello nicolasff,

We have tried to configure webdis.conf and set verbosity to 4. After webdis receiving the POST request  webdis log just display as "/" below, could you please clarify if it's the way to display POST data message in the log?

    [6029] 09 Apr 04:56:50 35 Webdis 0.1.2-dev up and running
    [6029] 09 Apr 04:57:38 0 /
    [6029] 09 Apr 04:58:20 0 /
    [6029] 09 Apr 05:07:40 0 /

Best regards,
Ukrit H.

**Comment by nicolasff** [comment]
Hi,

Web servers usually do not log the POST message and this is the same for Webdis.
