### ISSUE TITLE
Implementing access control 

### ISSUE THREAD

**Issue by ronisegoly** [nicolasff/webdis#119]
Can someone explain please explain how to implement access control in webd.is?
I have redis server on my google cloud
Does webd.is have its own access control aside from redis?
I just added password to my redis server

**Comment by nicolasff** [comment]
Please have a look at the documentation here: https://github.com/nicolasff/webdis#acl

**Comment by ronisegoly** [comment]
I have seen it but honestly got lost, and I am layman 
Is it separated from redis server access control mechanism?
If that is the case, please explain how do I implement it.
