### ISSUE TITLE
Operation against a key holding the wrong kind of value in redis when pushing data on a list

### ISSUE THREAD

**Issue by ashuthinks** [nicolasff/webdis#121]
Created redis list and setting key like following getting me error

   public async Task MyMethod<T>()
            {
        RedisList<string> list = new RedisList<string>(Settings, typeof(T).Name.ToString());
string mykey = "myId";
await list.LeftPush(mykey);
getting following error :

Result Message: StackExchange.Redis.RedisServerException : ERR Operation against a key holding the wrong kind of value

**Comment by nicolasff** [comment]
This is because your key `myId` is not a list, you need to create it with `LPUSH` first. You'd have better luck asking for advice on StackOverflow or the redis mailing list.
