### ISSUE TITLE
cannot do make have libevent issue 

### ISSUE THREAD

**Issue by dragnot** [nicolasff/webdis#141]
I have libevent installed but i cannot get it to work on RHEL 7. do i need specific version ?

redislabadm@ctoapp6 webdis-master]$ make
cc -c -O0 -ggdb -Wall -Wextra -I. -Ijansson/src -Ihttp-parser -o webdis.o webdis.c
In file included from webdis.c:1:0:
server.h:4:19: fatal error: event.h: No such file or directory
 #include <event.h>
                   ^
compilation terminated.
make: *** [webdis.o] Error 1
[redislabadm@ctoapp6 webdis-master]$ sudo instal libevent-*
sudo: instal: command not found
[redislabadm@ctoapp6 webdis-master]$ sudo install libevent-*
install: missing destination file operand after ‘libevent-*’
Try 'install --help' for more information.
[redislabadm@ctoapp6 webdis-master]$ sudo yum install libevent-*
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Package libevent-2.0.21-4.el7.x86_64 already installed and latest version
Nothing to do
[redislabadm@ctoapp6 webdis-master]$ make clean 
rm -f webdis.o cmd.o worker.o slog.o server.o acl.o md5/md5.o sha1/sha1.o http.o client.o websocket.o pool.o conf.o formats/json.o formats/raw.o formats/common.o formats/custom-type.o hiredis/hiredis.o hiredis/sds.o hiredis/net.o hiredis/async.o hiredis/read.o hiredis/dict.o jansson/src/dump.o jansson/src/error.o jansson/src/hashtable.o jansson/src/load.o jansson/src/strbuffer.o jansson/src/utf.o jansson/src/value.o jansson/src/variadic.o http-parser/http_parser.o b64/cencode.o webdis
[redislabadm@ctoapp6 webdis-master]$ make all
cc -c -O0 -ggdb -Wall -Wextra -I. -Ijansson/src -Ihttp-parser -o webdis.o webdis.c
In file included from webdis.c:1:0:
server.h:4:19: fatal error: event.h: No such file or directory
 #include <event.h>
                   ^
compilation terminated.
make: *** [webdis.o] Error 1
[redislabadm@ctoapp6 webdis-master]$ yum list libevent
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Repo rhel-7-server-rpms forced skip_if_unavailable=True due to: /etc/pki/entitlement/8137755762607495637-key.pem
Repo rhel-7-server-rt-beta-rpms forced skip_if_unavailable=True due to: /etc/pki/entitlement/8137755762607495637-key.pem
Repo rhel-7-server-rt-rpms forced skip_if_unavailable=True due to: /etc/pki/entitlement/8137755762607495637-key.pem
Installed Packages
libevent.i686                                                                                 2.0.21-4.el7                                                                               @rhel-7-server-rpms
libevent.x86_64                                                                               2.0.21-4.el7                                                                               @rhel-7-server-rpms

**Comment by nicolasff** [comment]
This is probably a more appropriate question for a RHEL support forum.
