### ISSUE TITLE
websocket does not handle multiple requests in a packet

### ISSUE THREAD

**Issue by granolamatt** [nicolasff/webdis#159]
While using chrome and subscribing to multiple (64 was my case) keys in a for loop, webdis will drop requests when the requests are grouped into a single network packet.  I assume that the grouping is because of Nagle's algorithm.

If I change the if statement to a while statement in websocket.c function ws_add_data it fixes my problem.  I am submitting a pull request as well for this issue.

**Comment by nicolasff** [comment]
Let's close this one to have a single issue tracking this bug.
