### ISSUE TITLE
Error on running `make`

### ISSUE THREAD

**Issue by shubhambhattar** [nicolasff/webdis#163]
Getting this error after running `make`
```

$ make
cc -c -O0 -ggdb -Wall -Wextra -I. -Ijansson/src -Ihttp-parser -o webdis.o webdis.c
In file included from webdis.c:1:
./server.h:4:10: fatal error: 'event.h' file not found
#include <event.h>
         ^~~~~~~~~
1 error generated.
make: *** [webdis.o] Error 1
```

**Comment by nicolasff** [comment]
Hi Shubham,

You need to install the libevent headers, as described in the [README](https://github.com/nicolasff/webdis#about).  If you're on Ubuntu, you can try `sudo apt-get install libevent-dev` before running `make`.
