### ISSUE TITLE
docker file to pass in redis host and port as ENV variables instead of setting up in webdis.json

### ISSUE THREAD

**Issue by zcaudate** [nicolasff/webdis#181]
I'd like to be able to spin up a docker instance of webdis and connect it to an already existing redis server.

Currently it's a bit difficult to do that. Being able to pass in ENV variables will make it easier.

**Comment by nicolasff** [comment]
Hi @zcaudate,

Sorry for the late response. You can create a config file where the `redis_host` field points to an environment variable; see [the documentation for this feature here](https://github.com/nicolasff/webdis#environment-variables).

Your `webdis.json` should look something like this:
```json
{
	"redis_host": "$REDIS_HOST",
	"redis_port": "$REDIS_PORT",
}
```

**Comment by zcaudate** [comment]
Ah awesome. That makes a lot of sense. Thanks heaps.
