### ISSUE TITLE
Connection: close triggers a freeze for payloads bigger than certain limit

### ISSUE THREAD

**Issue by przemek-pokrywka** [nicolasff/webdis#194]
Thanks for webdis, I like it a lot. I spotted the following issue when I put webdis behind a nginx, which I use for reverse-proxying:

If I send a PUT with some small payload, then webdis is fine, even when the `Connection: close` header is present:
```shell
(echo "[1"; yes ",1" | head -n 1957; echo "]" )  | curl -XPUT http://172.17.0.2:7379/SET/toobig -d @- -H "Connection: close"
```
but if the payload is bigger, then the connection hangs and eventually times out:
```shell
(echo "[1"; yes ",1" | head -n 1958; echo "]" )  | curl -XPUT http://172.17.0.2:7379/SET/toobig -d @- -H "Connection: close"
```
finally the problem goes away if I remove the `Connection: close` header.
```shell
(echo "[1"; yes ",1" | head -n 1958; echo "]" )  | curl -XPUT http://172.17.0.2:7379/SET/toobig -d @-
```

This is a problem, because the default configuration of nginx does append the `Connection: close`.
I worked that around by instructing nginx to send `Connection: keep-alive` instead:
```
proxy_set_header Connection keep-alive;
```

but I think that this is better addressed at webdis directly. For start it might be good to add that to webdis known issues in the docs.

**Comment by jessie-murray** [comment]
@nicolasff sure, I can try to find it. I wonder if the additional step with the `100 Continue` might have something to do with the issue. At least it will be easy to add a new test case for it once we have a patch to test :)
