### ISSUE TITLE
hiredis  &&  redis

### ISSUE THREAD

**Issue by chenshiy1** [nicolasff/webdis#208]
Hello author，first of all Thank you for your work and dedication。and I have a question，How does webdis use native Redis instead of Hiredis，thanks for your reply。

**Comment by nicolasff** [comment]
Hello @chenshiy1,

I don't understand your question. I'm not sure what "native Redis" is but you can't really compare Redis and Hiredis: Redis is an in-memory key-value store and Hiredis is a C library used to connect to Redis and query it.
Webdis uses Hiredis to query Redis.

Something like this:
```

  ┌───────────────────────────┐            ┌──────────────────┐
  │                           │            │                  │
  │             ┌──────────┐  │   Query    │                  │
  │             │          ├──┼───────────►│                  │
  │   Webdis    │ Hiredis  │  │            │      Redis       │
  │             │          │◄─┼────────────┤                  │
  │             └──────────┘  │  Response  │                  │
  │                           │            │                  │
  └───────────────────────────┘            └──────────────────┘
```

Does this answer your question?
