### ISSUE TITLE
protected-mode in the SSL example GIST has wrong value

### ISSUE THREAD

**Issue by tomsour1s** [nicolasff/webdis#243]
Hey @nicolasff,
I was playing around with your SSL example webdis-redis-docker-compose-ssl.md today.

Here: https://github.com/nicolasff/webdis/blob/4b66bcf85bd4450575b4286aab9e9c58f7cebc5e/docs/webdis-redis-docker-compose-ssl.md?plain=1#L193 you mention that `protected-mode` should be set to `no`.

But in the linked GIST: https://github.com/nicolasff/webdis/blob/4b66bcf85bd4450575b4286aab9e9c58f7cebc5e/docs/webdis-redis-docker-compose-ssl.md?plain=1#L207 `protected-mode` is set to `yes`.

-> https://gist.github.com/nicolasff/513d3ebd9d6f4268d6deb1d979fa44b8?plain=1#file-redis-conf-L94 This leads to errors when starting the service.

I created a pull request which links to a GIST where `protected-mode` is set to `no`. Or you just fix your GIST :).

Have a good day.

**Comment by nicolasff** [comment]
Hey @astrobrot, thanks for reporting this issue!
I think I'd like to keep the Gist link pointing to my account, and unfortunately it's not possible to create a PR for a Gist so I'll bring in your fix and credit you on the same page.
