### ISSUE TITLE
Reading the keys and values (HGETALL) of a redis hash over the websocket

### ISSUE THREAD

**Issue by Yawarzy** [nicolasff/webdis#249]
Hi,

Is it possible to access the data inside a redis hash over the websocket using the webdis ? We are able to subscribe to a redis channel over the websocket, and get the messages from the server over intervals. But can the same be done for a redis hash ?

Thanks.

**Comment by nicolasff** [comment]
Hello,

My apologies for the late reply.
You can definitely call `HGETALL` over Websocket, there is nothing special about this command that would prevent it. `GET`, `SET`, `PING`, `HGETALL`… there are no differences that would impact the way they work over Websockets.

Below is a screenshot of a local test I ran after quickly adding support for `HGETALL` to the HTML demo in the Webdis repo (`tests/websocket.html`). You can find the entire diff I used [in this Gist](https://gist.github.com/nicolasff/2fdf06600b7448336fe2eeee43913fcc).

And here's `HGETALL` being requested over Websocket, with the expected reply coming back over the same channel: 
![Screenshot 2024-09-15 at 22 10 14](https://github.com/user-attachments/assets/935f965b-e4c0-4bf8-8ca2-5a457e944f58)

Seeing that this quick demo works and not expecting anything different to happen with `HGETALL`, it's a bit difficult to tell exactly what you're seeing go wrong, if anything. Is there something specific that you've tried that didn't work? This would help me reproduce the issue.

Thanks!

**Comment by nicolasff** [comment]
Before closing this, I figured I might as well share the way I added `HGETALL` in the demo shown above: see commit https://github.com/nicolasff/webdis/commit/5bd37d8fd2118463a97456395728a418c2125010, and the branch https://github.com/nicolasff/webdis/tree/websockets-hgetall-demo.
