### ISSUE TITLE
Logging Not Working

### ISSUE THREAD

**Issue by razzam21** [nicolasff/webdis#65]
{
        "redis_host":   "127.0.0.1",
        "redis_port":   6379,
        "redis_auth":   null,
        "http_host":    "192.168.0.110",
        "http_port":    7369,
        "threads":      1,
        "pool_size": 10,
        "daemonize":    true,
        "websockets":   false,
        "database":     0,
        "acl": [
                {
                        "disabled":     ["DEBUG"]
                },
                {
                        "http_basic_auth":      "user:password",
                        "enabled":              ["DEBUG"]
                }
        ],
        "verbosity": 0,
        "logfile": "/var/log/webdis/webdis.log"
}

The directory permissions as set to 777 and the log file permissions are set to 777.  I also tried different numbers in verbosity.  And no luck.  Any ideas what I am doing wrong?

I cloned the git repository and compiled the code on my server.  It runs but just doesn't log.  I am having some issues and logging would be a huge help.

**Comment by wiwat-tharateeraparb** [comment]
Does Webdis log any PUBLISH command?

**Comment by wiwat-tharateeraparb** [comment]
Seems like it does not log POST method, only GET.
